// src/App.tsx
{
  /* <template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <HelloWorld msg="Hello Vue 3.0 + Vite" />
</template>

<script> */
}
import HelloWorld from "./components/HelloWorld.vue";

export default {
  name: "App",
  components: {
    HelloWorld,
  },
  setup() {
    return () => (
      <>
        <HelloWorld msg="Hello Vue 3.0 + vite" />
      </>
    );
  },
};

// src/App.vue
<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <a-button :loading="loading" @click="handleClick">ant-design </a-button>
  <!-- <router-view /> -->
</template>

<script lang="ts">
import { Button as AButton } from "ant-design-vue";
import { ref } from "vue";
export default {
  name: "App",
  components: { AButton },
  setup() {
    const loading = ref(false);
    const handleClick = () => {
      console.log("1231");
      loading.value = !loading.value;
    };
    return { loading, handleClick };
  },
};
</script>
